### ISSUE TITLE
jsk_rosbag_tools failing in CI

### ISSUE THREAD

**Issue by lucasw** [lucasw/ros_from_src#18]
Works on my desktop system but may have some different dependencies- do I have a pip installed numpy?

```
2023-01-20T17:47:16.5150204Z    command: /home/runner/work/ros_from_src/ros_from_src/base_catkin_ws/build/jsk_rosbag_tools/venv/bin/python /home/runner/work/ros_from_src/ros_from_src/base_catkin_ws/build/jsk_rosbag_tools/venv/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpqxwlj69u
2023-01-20T17:47:16.5150790Z        cwd: /tmp/pip-install-flsgr19q/numpy
2023-01-20T17:47:16.5151039Z   Complete output (34 lines):
2023-01-20T17:47:16.5151263Z   Running from numpy source directory.
2023-01-20T17:47:16.5151512Z   setup.py:67: DeprecationWarning:
2023-01-20T17:47:16.5151712Z   
2023-01-20T17:47:16.5151942Z     `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
2023-01-20T17:47:16.5152268Z     of the deprecation of `distutils` itself. It will be removed for
2023-01-20T17:47:16.5152588Z     Python >= 3.12. For older Python versions it will remain present.
2023-01-20T17:47:16.5152904Z     It is recommended to use `setuptools < 60.0` for those Python versions.
2023-01-20T17:47:16.5153169Z     For more details, see:
2023-01-20T17:47:16.5153474Z       https://numpy.org/devdocs/reference/distutils_status_migration.html
2023-01-20T17:47:16.5153714Z   
2023-01-20T17:47:16.5154202Z   
2023-01-20T17:47:16.5154412Z     import numpy.distutils.command.sdist
2023-01-20T17:47:16.5154653Z   Traceback (most recent call last):
2023-01-20T17:47:16.5155221Z     File "/home/runner/work/ros_from_src/ros_from_src/base_catkin_ws/build/jsk_rosbag_tools/venv/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
2023-01-20T17:47:16.5155786Z       main()
2023-01-20T17:47:16.5156309Z     File "/home/runner/work/ros_from_src/ros_from_src/base_catkin_ws/build/jsk_rosbag_tools/venv/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
2023-01-20T17:47:16.5156772Z       json_out['return_val'] = hook(**hook_input['kwargs'])
2023-01-20T17:47:16.5157437Z     File "/home/runner/work/ros_from_src/ros_from_src/base_catkin_ws/build/jsk_rosbag_tools/venv/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
2023-01-20T17:47:16.5157881Z       return _build_backend().build_wheel(wheel_directory, config_settings,
2023-01-20T17:47:16.5158327Z     File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 230, in build_wheel
2023-01-20T17:47:16.5158713Z       return self._build_with_temp_dir(['bdist_wheel'], '.whl',
2023-01-20T17:47:16.5159207Z     File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
2023-01-20T17:47:16.5159494Z       self.run_setup()
2023-01-20T17:47:16.5159851Z     File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 267, in run_setup
2023-01-20T17:47:16.5160156Z       super(_BuildMetaLegacyBackend,
2023-01-20T17:47:16.5160545Z     File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
2023-01-20T17:47:16.5160912Z       exec(compile(code, __file__, 'exec'), locals())
2023-01-20T17:47:16.5161162Z     File "setup.py", line 479, in <module>
2023-01-20T17:47:16.5161388Z       setup_package()
2023-01-20T17:47:16.5161623Z     File "setup.py", line 458, in setup_package
2023-01-20T17:47:16.5161837Z       generate_cython()
2023-01-20T17:47:16.5162068Z     File "setup.py", line 250, in generate_cython
2023-01-20T17:47:16.5162301Z       raise RuntimeError(msg)
2023-01-20T17:47:16.5162760Z   RuntimeError: Building NumPy requires Cython >= 0.29.30, found 0.29.28 at /usr/lib/python3/dist-packages/Cython/__init__.py
2023-01-20T17:47:16.5163157Z   ----------------------------------------[0m
2023-01-20T17:47:16.5163475Z [31m  ERROR: Failed building wheel for numpy[0m
2023-01-20T17:47:16.5163885Z [31mERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly[0m
2023-01-20T17:47:16.5164196Z Traceback (most recent call last):
2023-01-20T17:47:16.5164551Z   File "/home/runner/work/ros_from_src/ros_from_src/base_catkin_ws/devel/lib/catkin_virtualenv/venv_install", line 15, in <module>
2023-01-20T17:47:16.5164984Z     exec(compile(fh.read(), python_script, 'exec'), context)
2023-01-20T17:47:16.5165379Z   File "/home/runner/work/ros_from_src/ros_from_src/base_catkin_ws/src/other/catkin_virtualenv/catkin_virtualenv/scripts/venv_install", line 43, in <module>
2023-01-20T17:47:16.5165710Z     venv.install(
2023-01-20T17:47:16.5166072Z   File "/home/runner/work/ros_from_src/ros_from_src/base_catkin_ws/src/other/catkin_virtualenv/catkin_virtualenv/src/catkin_virtualenv/venv.py", line 114, in install
2023-01-20T17:47:16.5166505Z     run_command(command + ["-r", req], check=True)
2023-01-20T17:47:16.5166746Z   File "<string>", line 37, in run_command
2023-01-20T17:47:16.5167016Z   File "/usr/lib/python3.10/subprocess.py", line 524, in run
2023-01-20T17:47:16.5167311Z     raise CalledProcessError(retcode, process.args,
2023-01-20T17:47:16.5168199Z subprocess.CalledProcessError: Command '['/home/runner/work/ros_from_src/ros_from_src/base_catkin_ws/build/jsk_rosbag_tools/venv/bin/python', '-m', 'pip', 'install', '-qq', '--retries', '10', '--timeout', '30', '-r', '/home/runner/work/ros_from_src/ros_from_src/base_catkin_ws/src/other/jsk_common/jsk_rosbag_tools/requirements.txt']' returned non-zero exit status 1.
2023-01-20T17:47:16.5168884Z make[2]: *** [CMakeFiles/jsk_rosbag_tools_generate_virtualenv.dir/build.make:88: venv/bin/activate] Error 1
2023-01-20T17:47:16.5169267Z make[2]: *** Deleting file 'venv/bin/activate'
2023-01-20T17:47:16.5169609Z make[1]: *** [CMakeFiles/Makefile2:268: CMakeFiles/jsk_rosbag_tools_generate_virtualenv.dir/all] Error 2
2023-01-20T17:47:16.5169907Z make: *** [Makefile:146: all] Error 2
2023-01-20T17:47:16.5170459Z cd /home/runner/work/ros_from_src/ros_from_src/base_catkin_ws/build/jsk_rosbag_tools; catkin build --get-env jsk_rosbag_tools | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -
2023-01-20T17:47:16.5170941Z 
2023-01-20T17:47:16.5171059Z ...............................................................................
2023-01-20T17:47:16.5171441Z Failed << jsk_rosbag_tools:make  ```

**Comment by lucasw** [comment]
I have 1.21.5-1ubuntu22.04.1 apt installed, but 1.23.1 pip installed is overlaying it
