### ISSUE TITLE
Build ROS on Ubuntu 22.04 when it is available

### ISSUE THREAD

**Issue by lucasw** [lucasw/ros_from_src#2]

**Comment by lucasw** [comment]
The dockerfile works with 20.04, but reveals an issue with 21.04 - solving it could be necessary for building on 22.04 later:

```
docker build --build-arg IMAGE=ubuntu:21.04 . -t ros2104
...
-- BUILD_SHARED_LIBS is on
Traceback (most recent call last):
  File "/build/cmake_modules/catkin_generated/generate_cached_setup.py", line 12, in <module>
    from catkin.environment_cache import generate_environment_script
ModuleNotFoundError: No module named 'catkin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/cmake_modules/catkin_generated/generate_cached_setup.py", line 20, in <module>
    from catkin.environment_cache import generate_environment_script
ModuleNotFoundError: No module named 'catkin'
CMake Error at /opt/ros/noetic/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/usr/bin/python
  "/build/cmake_modules/catkin_generated/generate_cached_setup.py") returned
  error code 1
Call Stack (most recent call first):
  /opt/ros/noetic/share/catkin/cmake/all.cmake:208 (safe_execute_process)
  /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:4 (find_package)
```

**Comment by lucasw** [comment]
Trying 21.10 now:

```
docker build --build-arg IMAGE=ubuntu:21.10 . -t ros2110
...
-- BUILD_SHARED_LIBS is on
Traceback (most recent call last):
  File "/build/cmake_modules/catkin_generated/generate_cached_setup.py", line 12, in <module>
    from catkin.environment_cache import generate_environment_script
ModuleNotFoundError: No module named 'catkin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/cmake_modules/catkin_generated/generate_cached_setup.py", line 20, in <module>
    from catkin.environment_cache import generate_environment_script
ModuleNotFoundError: No module named 'catkin'
CMake Error at /opt/ros/noetic/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/usr/bin/python
  "/build/cmake_modules/catkin_generated/generate_cached_setup.py") returned
  error code 1
Call Stack (most recent call first):
  /opt/ros/noetic/share/catkin/cmake/all.cmake:208 (safe_execute_process)
  /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:4 (find_package)
```

**Comment by lucasw** [comment]
Python 3.8 - > 3.9, half fixed via

```
docker build --build-arg IMAGE=ubuntu:21.10 --build-arg PYTHON_MINOR_VERSION=9 . -t ros2110
```

21.10 builds, see a few of these:

```
Warnings << topic_tools:make /catkin_ws/logs/topic_tools/build.make.000.log    
In file included from /usr/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
                 from /usr/include/boost/smart_ptr/detail/yield_k.hpp:23,
                 from /usr/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
                 from /usr/include/boost/smart_ptr/detail/spinlock.hpp:42,
                 from /usr/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:29,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /catkin_ws/src/ros_comm/clients/roscpp/include/ros/forwards.h:37,
                 from /catkin_ws/devel/.private/roscpp/include/ros/common.h:37,
                 from /catkin_ws/src/ros_comm/clients/roscpp/include/ros/ros.h:43,
                 from /catkin_ws/src/ros_comm/tools/topic_tools/include/topic_tools/shape_shifter.h:38,
                 from /catkin_ws/src/ros_comm/tools/topic_tools/src/shape_shifter.cpp:35:
/usr/include/boost/bind.hpp:36:1: note: ‘#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.’
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
```

**Comment by lucasw** [comment]
https://github.com/ros/geometry/pull/ 233 and others

https://github.com/ros-o

**Comment by lucasw** [comment]
```
docker pull ubuntu:22.04
```

**Comment by lucasw** [comment]
```
Warnings << rosbag_storage:make /catkin_ws/logs/rosbag_storage/build.make.000.log
/catkin_ws/src/ros_comm/tools/rosbag_storage/src/aes_encryptor.cpp: In member function ‘virtual void rosbag::AesCbcEncryptor::initialize(const rosbag::Bag&, const string&)’:
/catkin_ws/src/ros_comm/tools/rosbag_storage/src/aes_encryptor.cpp:188:28: warning: ‘int AES_set_encrypt_key(const unsigned char*, int, AES_KEY*)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  188 |         AES_set_encrypt_key(&symmetric_key_[0], AES_BLOCK_SIZE*8, &aes_encrypt_key_);
      |         ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /catkin_ws/src/ros_comm/tools/rosbag_storage/include/rosbag/aes_encryptor.h:41,
                 from /catkin_ws/src/ros_comm/tools/rosbag_storage/src/aes_encryptor.cpp:36:
/usr/include/openssl/aes.h:51:5: note: declared here
   51 | int AES_set_encrypt_key(const unsigned char *userKey, const int bits,
      |     ^~~~~~~~~~~~~~~~~~~
/catkin_ws/src/ros_comm/tools/rosbag_storage/src/aes_encryptor.cpp: In member function ‘virtual uint32_t rosbag::AesCbcEncryptor::encryptChunk(uint32_t, uint64_t, rosbag::ChunkedFile&)’:
```

**Comment by lucasw** [comment]
This is failing in the github action:

```
CMake Error at /home/runner/work/ros_from_src/ros_from_src/staging/catkin_ws/devel/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "rosunit" with any
  of the following names:

    rosunitConfig.cmake
    rosunit-config.cmake

  Add the installation prefix of "rosunit" to CMAKE_PREFIX_PATH or set
  "rosunit_DIR" to a directory containing one of the above files.  If
  "rosunit" provides a separate development package or SDK, be sure it has
  been installed.
```

Fixed, the package containing rosunit has both manual cmake install components and catkin build components, so have to put it in catkin ws

**Comment by lucasw** [comment]
Now trying to build most of my packages and forks in 20.04 (not in docker):

Not sure if a catkin clean would avoid this:

```Errors     << joy_feedback_ros:cmake /home/lucasw/ros_from_src_catkin_ws/logs/joy_feedback_ros/build.cmake.000.log                                                                                                     
CMake Error at /home/lucasw/ros_from_src_catkin_ws/src/lucasw/joy_feedback_ros/CMakeLists.txt:111 (add_dependencies):
  The dependency target "joy_feedback_ros_generate_messages_cpp" of target
  "joy_feedback" does not exist.
```

I think something with message generation is broken- that package (and also fuse_msgs) are not setting up message building properly in their CMakeLists.txts?

No none of the messages are getting generated, catkin build std_msgs only produces js and `.l` files

```
devel/share/gennodejs/ros/std_msgs/msg/Float32MultiArray.js
devel/share/gennodejs/ros/std_msgs/msg/Float32.js
devel/share/roseus/ros/std_msgs/msg/Float32.l
devel/share/roseus/ros/std_msgs/msg/Float32MultiArray.l
```

-> Wasn't fully building `genpy`

**Comment by lucasw** [comment]
```
_______________________________________________________________________________________________________________________________________________________________________________________________________________________
Warnings   << qt_gui_cpp:make /home/lucasw/ros_from_src_catkin_ws/logs/qt_gui_cpp/build.make.000.log                                                                                                                   
qt.shiboken: (typesystem) Unable to locate Clang's built-in include directory (neither by checking the environment variables LLVM_INSTALL_DIR, CLANG_INSTALL_DIR  nor running llvm-config). This may lead to parse errors.
(typesystem) clang_parseTranslationUnit2(0x0, cmd[28]=-fPIC -Wno-constant-logical-operand -std=c++14 -I/home/lucasw/ros_from_src_catkin_ws/src/ros_core/qt_gui_core/qt_gui_cpp/include -I/home/lucasw/ros_from_src_catkin_ws/src/ros_core/qt_gui_core/qt_gui_cpp/include -I/home/lucasw/ros_from_src_catkin_ws/src/ros/roscpp_core/cpp_common/include -I/home/lucasw/ros_from_src_catkin_ws/src/ros_core/ros/core/roslib/include -I/home/lucasw/ros_from_src_catkin_ws/src/ros/roscpp_core/rostime/include -I/home/lucasw/ros_from_src_catkin_ws/src/ros/rosconsole/include -I/home/lucasw/ros_from_src_catkin_ws/src/ros_core/pluginlib/pluginlib/include -I/home/lucasw/own/build/ros_from_src/ros/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/usr/include/PySide2 -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include /tmp/global_fthQxC.hpp)
qt.shiboken: (typesystem) While traversing QOpenGLShaderProgram: setAttributeArray(int,const float*,int,int): Cannot use parameter 2 as an array: <array> modification already applied.
qt.shiboken: (typesystem) class 'QAccessibleWidget' inherits from unknown base class 'QAccessibleActionInterface'
qt.shiboken: (typesystem) class not found for setup inheritance 'QAccessibleActionInterface'
```

**Comment by lucasw** [comment]
```
Warnings   << rviz:make /home/lucasw/ros_from_src_catkin_ws/logs/rviz/build.make.000.log                                                                                                                               
In file included from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qaction.h:47,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:47,
                 from /usr/share/sip/PyQt5/QtWidgets/qmenu.sip:26:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h: In constructor ‘QVariant::QVariant(QVariant&&)’:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h:275:25: warning: implicitly-declared ‘constexpr QVariant::Private& QVariant::Private::operator=(const QVariant::Private&)’ is deprecated [-Wdeprecated-copy]
  275 |     { other.d = Private(); }
      |                         ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h:401:16: note: because ‘QVariant::Private’ has user-provided ‘QVariant::Private::Private(const QVariant::Private&)’
  401 |         inline Private(const Private &other) Q_DECL_NOTHROW
      |                ^~~~~~~
In file included from /usr/share/sip/PyQt5/QtWidgets/qstyleoption.sip:560:
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qstyleoption.h: In copy constructor ‘QStyleOptionFocusRect::QStyleOptionFocusRect(const QStyleOptionFocusRect&)’:
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qstyleoption.h:120:103: warning: implicitly-declared ‘QStyleOptionFocusRect& QStyleOptionFocusRect::operator=(const QStyleOptionFocusRect&)’ is deprecated [-Wdeprecated-copy]
```

**Comment by lucasw** [comment]
Need kinetic-devel in control_msgs

**Comment by lucasw** [comment]
Needed these to build most of my stuff, but this is missing a few repos from another vcs export, add those also

[additional_ros_repos.yaml.txt](https://github.com/lucasw/ros_from_src/files/8105490/additional_ros_repos.yaml.txt)

Separate out the ones that are already in ros-o

**Comment by lucasw** [comment]
Need to `CATKIN_IGNORE` jsk `sound_classification` for now, avoid catkin virtualenv dependency

also `audio_video_recorder`


```
touch jsk_common/jsk_tilt_laser/CATKIN_IGNORE
touch jsk_common/jsk_topic_tools/CATKIN_IGNORE
touch jsk_recognition/jsk_recognition_utils/CATKIN_IGNORE
touch jsk_recognition/resized_image_transport/CATKIN_IGNORE
touch jsk_recognition/imagesift/CATKIN_IGNORE
touch jsk_recognition/jsk_perception/CATKIN_IGNORE
touch jsk_recognition/jsk_rviz_plugins/CATKIN_IGNORE
touch jsk_recognition/jsk_pcl_ros/CATKIN_IGNORE
touch jsk_recognition/jsk_pcl_ros_utils/CATKIN_IGNORE
```

The jsk rviz plugins are what I really want, so having to disable them means none of the jsk stuff is needed until this is fixed.

**Comment by lucasw** [comment]
```
Errors     << jsk_topic_tools:make /home/lucasw/ros_from_src_catkin_ws/logs/jsk_topic_tools/build.make.003.log                                                                                                         
In file included from /home/lucasw/ros_from_src_catkin_ws/src/ros_core/jsk_common/jsk_topic_tools/include/jsk_topic_tools/vital_checker_nodelet.h:40,
                 from /home/lucasw/ros_from_src_catkin_ws/src/ros_core/jsk_common/jsk_topic_tools/src/vital_checker_nodelet.cpp:37:
/home/lucasw/ros_from_src_catkin_ws/src/ros_core/jsk_common/jsk_topic_tools/include/jsk_topic_tools/diagnostic_nodelet.h:40:10: fatal error: diagnostic_updater/diagnostic_updater.h: No such file or directory
   40 | #include <diagnostic_updater/diagnostic_updater.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by lucasw** [comment]
Packages that aren't yet in debian that I need:

[unreleased_ros_repos.yaml.txt](https://github.com/lucasw/ros_from_src/files/8111219/unreleased_ros_repos.yaml.txt)

**Comment by lucasw** [comment]
Now catkin can't find message_generation, though it is installed via `ros-message-generation`
