### ISSUE TITLE
fiducial_msgs failing in github action after being built in earlier step

### ISSUE THREAD

**Issue by lucasw** [lucasw/ros_from_src#27]
When fiducials is built in devel before this it is successful, but fails during the install build:

```
2023-08-25T18:55:16.3201765Z Errors << fiducial_msgs:loadenv /home/runner/work/ros_from_src/ros_from_src/install_base_catkin_ws/logs/fiducial_msgs/build.loadenv.000.log
2023-08-25T18:55:16.3202185Z Traceback (most recent call last):
2023-08-25T18:55:16.3202939Z   File "/home/runner/other/install/lib/python3.10/site-packages/catkin_tools/execution/stages.py", line 177, in function_proxy
2023-08-25T18:55:16.3203385Z     return function(logger, event_queue, *args, **kwargs)
2023-08-25T18:55:16.3203914Z   File "/home/runner/other/install/lib/python3.10/site-packages/catkin_tools/jobs/utils.py", line 113, in loadenv
2023-08-25T18:55:16.3204327Z     envs.append(get_resultspace_environment(
2023-08-25T18:55:16.3204917Z   File "/home/runner/other/install/lib/python3.10/site-packages/catkin_tools/resultspace.py", line 130, in get_resultspace_environment
2023-08-25T18:55:16.3205425Z     lines = subprocess.check_output(command, cwd=os.getcwd(), env=base_env, shell=True)
2023-08-25T18:55:16.3205823Z   File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
2023-08-25T18:55:16.3206214Z     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
2023-08-25T18:55:16.3206591Z   File "/usr/lib/python3.10/subprocess.py", line 526, in run
2023-08-25T18:55:16.3206926Z     raise CalledProcessError(retcode, process.args,
2023-08-25T18:55:16.3207650Z subprocess.CalledProcessError: Command '/home/runner/work/ros_from_src/ros_from_src/install_base_catkin_ws/install/env.sh /bin/bash -c "env --null"' returned non-zero exit status 2.
2023-08-25T18:55:16.3208034Z 
2023-08-25T18:55:16.3208159Z Stage `loadenv` failed with arguments:
2023-08-25T18:55:16.3222192Z   job_env: {'ROS_VERSION': '1', 'SELENIUM_JAR_PATH': '/usr/share/java/selenium-server.jar', 'CONDA': '/usr/share/miniconda', 'GITHUB_WORKSPACE': '/home/runner/work/ros_from_src/ros_from_src', 'JAVA_HOME_11_X64': '/usr/lib/jvm/temurin-11-jdk-amd64', 'PKG_CONFIG_PATH': '/home/runner/work/ros_from_src/ros_from_src/install_base_catkin_ws/install/lib/pkgconfig', 'ROS_PYTHON_VERSION': '3', 'GITHUB_PATH': '/home/runner/work/_temp/_runner_file_commands/add_path_8c938768-28d6-47c8-b43a-358f16ab1df1', 'GITHUB_ACTION': '__run_38', 'JAVA_HOME': '/usr/lib/jvm/temurin-11-jdk-amd64', 'GITHUB_RUN_NUMBER': '118', 'RUNNER_NAME': 'GitHub Actions 3', 'GRADLE_HOME': '/usr/share/gradle-8.3', 'GITHUB_REPOSITORY_OWNER_ID': '1334122', 'DEST': '/home/runner/other/install', 'XDG_CONFIG_HOME': '/home/runner/.config', 'DOTNET_SKIP_FIRST_TIME_EXPERIENCE': '1', 'ANT_HOME': '/usr/share/ant', 'JAVA_HOME_8_X64': '/usr/lib/jvm/temurin-8-jdk-amd64', 'GITHUB_TRIGGERING_ACTOR': 'lucasw', 'GITHUB_REF_TYPE': 'branch', 'ROS_PACKAGE_PATH': '/home/runner/work/ros_from_src/ros_from_src/install_base_catkin_ws/install/share', 'HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS': '3650', 'ROSLISP_PACKAGE_DIRECTORIES': '', 'ANDROID_NDK': '/usr/local/lib/android/sdk/ndk/25.2.9519653', 'BOOTSTRAP_HASKELL_NONINTERACTIVE': '1', 'PWD': '/home/runner/work/ros_from_src/ros_from_src/install_base_catkin_ws', 'PIPX_BIN_DIR': '/opt/pipx_bin', 'STATS_TRP': 'true', 'GOROOT_1_20_X64': '/opt/hostedtoolcache/go/1.20.7/x64', 'GITHUB_REPOSITORY_ID': '359979255', 'DEPLOYMENT_BASEPATH': '/opt/runner', 'GITHUB_ACTIONS': 'true', 'STATS_VMD': 'true', 'ANDROID_NDK_LATEST_HOME': '/usr/local/lib/android/sdk/ndk/25.2.9519653', 'SYSTEMD_EXEC_PID': '664', 'GITHUB_SHA': '07c0070761c90b811d75216b0948bc471bef5c26', 'GITHUB_WORKFLOW_REF': 'lucasw/ros_from_src/.github/workflows/ubuntu_22_04.yml@refs/heads/robot_state_publisher', 'POWERSHELL_DISTRIBUTION_CHANNEL': 'GitHub-Actions-ubuntu22', 'RUNNER_ENVIRONMENT': 'github-hosted', 'STATS_EXTP': 'https://provjobdsettingscdn.blob.core.windows.net/settings/provjobdsettings-0.5.154/provjobd.data', 'DOTNET_MULTILEVEL_LOOKUP': '0', 'STATS_TIS': 'mining', 'GITHUB_REF': 'refs/heads/robot_state_publisher', 'RUNNER_OS': 'Linux', 'GITHUB_REF_PROTECTED': 'false', 'HOME': '/home/runner', 'GITHUB_API_URL': 'https://api.github.com', 'LANG': 'C.UTF-8', 'ROS_ETC_DIR': '//etc/ros', 'RUNNER_TRACKING_ID': 'github_950e3e14-ae9f-4798-a827-4e613e086687', 'RUNNER_ARCH': 'X64', 'GOROOT_1_21_X64': '/opt/hostedtoolcache/go/1.21.0/x64', 'RUNNER_TEMP': '/home/runner/work/_temp', 'GITHUB_STATE': '/home/runner/work/_temp/_runner_file_commands/save_state_8c938768-28d6-47c8-b43a-358f16ab1df1', 'CMAKE_PREFIX_PATH': '/home/runner/work/ros_from_src/ros_from_src/install_base_catkin_ws/install', 'EDGEWEBDRIVER': '/usr/local/share/edge_driver', 'PYTHON_MAJOR_VERSION': '3', 'GITHUB_ENV': '/home/runner/work/_temp/_runner_file_commands/set_env_8c938768-28d6-47c8-b43a-358f16ab1df1', 'PYTHON_MINOR_VERSION': '10', 'GITHUB_EVENT_PATH': '/home/runner/work/_temp/_github_workflow/event.json', 'INVOCATION_ID': '7b6192892be644ed8f4a0977b085e3f2', 'GITHUB_EVENT_NAME': 'push', 'GITHUB_RUN_ID': '5977923595', 'JAVA_HOME_17_X64': '/usr/lib/jvm/temurin-17-jdk-amd64', 'ANDROID_NDK_HOME': '/usr/local/lib/android/sdk/ndk/25.2.9519653', 'GITHUB_STEP_SUMMARY': '/home/runner/work/_temp/_runner_file_commands/step_summary_8c938768-28d6-47c8-b43a-358f16ab1df1', 'HOMEBREW_NO_AUTO_UPDATE': '1', 'GITHUB_ACTOR': 'lucasw', 'NVM_DIR': '/home/runner/.nvm', 'SGX_AESM_ADDR': '1', 'GITHUB_RUN_ATTEMPT': '1', 'STATS_RDCL': 'true', 'ANDROID_HOME': '/usr/local/lib/android/sdk', 'GITHUB_GRAPHQL_URL': 'https://api.github.com/graphql', 'PYTHONPATH': '/home/runner/work/ros_from_src/ros_from_src/install_base_catkin_ws/install/lib/python3/dist-packages:/home/runner/other/install/lib/python3.10/site-packages/', 'RUNNER_USER': 'runner', 'ACCEPT_EULA': 'Y', 'STATS_UE': 'true', 'USER': 'runner', 'GITHUB_SERVER_URL': 'https://github.com', 'STATS_V3PS': 'true', 'PIPX_HOME': '/opt/pipx', 'GECKOWEBDRIVER': '/usr/local/share/gecko_driver', 'STATS_NM': 'true', 'STATS_EXT': 'true', 'CHROMEWEBDRIVER': '/usr/local/share/chromedriver-linux64', 'SHLVL': '1', 'ANDROID_SDK_ROOT': '/usr/local/lib/android/sdk', 'ROS_MASTER_URI': 'http://localhost:11311', 'VCPKG_INSTALLATION_ROOT': '/usr/local/share/vcpkg', 'GITHUB_ACTOR_ID': '1334122', 'RUNNER_TOOL_CACHE': '/opt/hostedtoolcache', 'ImageVersion': '20230821.1.0', 'DOTNET_NOLOGO': '1', 'GITHUB_WORKFLOW_SHA': '07c0070761c90b811d75216b0948bc471bef5c26', 'GITHUB_REF_NAME': 'robot_state_publisher', 'GITHUB_JOB': 'ubuntu2204', 'LD_LIBRARY_PATH': '/home/runner/work/ros_from_src/ros_from_src/install_base_catkin_ws/install/lib', 'XDG_RUNTIME_DIR': '/run/user/1001', 'AZURE_EXTENSION_DIR': '/opt/az/azcliextensions', 'PERFLOG_LOCATION_SETTING': 'RUNNER_PERFLOG', 'GITHUB_REPOSITORY': 'lucasw/ros_from_src', 'CHROME_BIN': '/usr/bin/google-chrome', 'ANDROID_NDK_ROOT': '/usr/local/lib/android/sdk/ndk/25.2.9519653', 'GOROOT_1_18_X64': '/opt/hostedtoolcache/go/1.18.10/x64', 'GITHUB_RETENTION_DAYS': '90', 'JOURNAL_STREAM': '8:17431', 'RUNNER_WORKSPACE': '/home/runner/work/ros_from_src', 'LEIN_HOME': '/usr/local/lib/lein', 'LEIN_JAR': '/usr/local/lib/lein/self-installs/leiningen-2.10.0-standalone.jar', 'GITHUB_ACTION_REPOSITORY': '', 'PATH': '/home/runner/work/ros_from_src/ros_from_src/install_base_catkin_ws/install/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/runner/other/install/bin', 'RUNNER_PERFLOG': '/home/runner/perflog', 'GITHUB_BASE_REF': '', 'GHCUP_INSTALL_BASE_PREFIX': '/usr/local', 'CI': 'true', 'SWIFT_PATH': '/usr/share/swift/usr/bin', 'ImageOS': 'ubuntu22', 'GITHUB_REPOSITORY_OWNER': 'lucasw', 'GITHUB_HEAD_REF': '', 'GITHUB_ACTION_REF': '', 'GOROOT_1_19_X64': '/opt/hostedtoolcache/go/1.19.12/x64', 'GITHUB_WORKFLOW': 'Ubuntu 22.04 build with debian ros packages along with source packages', 'DEBIAN_FRONTEND': 'noninteractive', 'ROS_DISTRO': 'Debian', 'GITHUB_OUTPUT': '/home/runner/work/_temp/_runner_file_commands/set_output_8c938768-28d6-47c8-b43a-358f16ab1df1', 'AGENT_TOOLSDIRECTORY': '/opt/hostedtoolcache', 'OLDPWD': '/home/runner/work/ros_from_src/ros_from_src', '_': '/home/runner/other/install/bin/catkin'}
2023-08-25T18:55:16.3234420Z   package: {'package_format': 2, 'name': 'fiducial_msgs', 'version': '0.12.0', 'version_compatibility': None, 'description': 'Package containing message definitions for fiducials', 'maintainers': [<catkin_pkg.package.Person object at 0x7fde2ea2e1d0>, <catkin_pkg.package.Person object at 0x7fde2ea2e200>], 'licenses': ['BSD'], 'urls': [], 'authors': [<catkin_pkg.package.Person object at 0x7fde2ea2e2c0>], 'build_depends': [Dependency(name='message_generation', evaluated_condition=True), Dependency(name='geometry_msgs', evaluated_condition=True), Dependency(name='sensor_msgs', evaluated_condition=True), Dependency(name='std_msgs', evaluated_condition=True), Dependency(name='tf', evaluated_condition=True)], 'buildtool_depends': [Dependency(name='catkin', evaluated_condition=True)], 'build_export_depends': [Dependency(name='message_runtime', evaluated_condition=True), Dependency(name='geometry_msgs', evaluated_condition=True), Dependency(name='sensor_msgs', evaluated_condition=True), Dependency(name='std_msgs', evaluated_condition=True), Dependency(name='tf', evaluated_condition=True)], 'buildtool_export_depends': [], 'exec_depends': [Dependency(name='message_runtime', evaluated_condition=True), Dependency(name='geometry_msgs', evaluated_condition=True), Dependency(name='sensor_msgs', evaluated_condition=True), Dependency(name='std_msgs', evaluated_condition=True), Dependency(name='tf', evaluated_condition=True)], 'test_depends': [], 'doc_depends': [], 'conflicts': [], 'replaces': [], 'group_depends': [], 'member_of_groups': [], 'exports': [], 'filename': '/home/runner/work/ros_from_src/ros_from_src/base_catkin_ws/src/other/fiducials/fiducial_msgs/package.xml'}
2023-08-25T18:55:16.3237110Z   context: <catkin_tools.context.Context object at 0x7fde300fbb20>
2023-08-25T18:55:16.3237337Z 
2023-08-25T18:55:16.3237466Z ...............................................................................
2023-08-25T18:55:16.3237807Z Failed << fiducial_msgs:loadenv                                   [ Exited with code 3 ]
```

**Comment by lucasw** [comment]
Ignoring euslisp-release, geneus, and jsk_roseus fixed the install build- could have an ignore_install.sh to still build packages that work in devel.
