### ISSUE TITLE
ros-one on Ubuntu 23.10

### ISSUE THREAD

**Issue by lucasw** [lucasw/ros_from_src#31]
Upgrading from 23.04

https://github.com/lucasw/ros_from_src/issues/30#issuecomment-1817897053

`locate` -> `plocate`

**Comment by lucasw** [comment]
```
In file included from /usr/include/gtest/gtest-message.h:57,
                 from /usr/include/gtest/gtest-assertion-result.h:46,
                 from /usr/include/gtest/gtest.h:64,
                 from /home/lucasw/base_catkin_ws/src/extra/geometry/tf/test/transform_listener_unittest.cpp:30:
/usr/include/gtest/internal/gtest-port.h:270:2: error: #error C++ versions less than C++14 are not supported.
  270 | #error C++ versions less than C++14 are not supported.
      |  ^~~~~
```

Need to use `git@github.com:ros-o/geometry.git` obese-devel instead of upstream noetic-devel

**Comment by lucasw** [comment]
```
Errors     << grid_map_filters:check /home/lucasw/install_base_catkin_ws/logs/grid_map_filters/build.check.005.log                                                                                                            
CMake Warning (dev) at /usr/share/catkin/cmake/python.cmake:7 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  /usr/share/catkin/cmake/all.cmake:164 (include)
  /usr/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:30 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:35 (find_package):
  Could not find a configuration file for package "TBB" that exactly matches
  requested version "2021.8.0".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/TBB/TBBConfig.cmake, version: 2021.9.0
    /lib/x86_64-linux-gnu/cmake/TBB/TBBConfig.cmake, version: 2021.9.0
```

relax requirement of tbb - added new commit to git@github.com:lucasw/grid_map tbb_2021

**Comment by lucasw** [comment]
```
Errors     << rviz:cmake /home/lucasw/install_base_catkin_ws/logs/rviz/build.cmake.002.log                                                                                                                                  
CMake Error at /usr/share/cmake-3.27/Modules/FindPkgConfig.cmake:607 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.27/Modules/FindPkgConfig.cmake:829 (_pkg_check_modules_internal)
  CMakeLists.txt:41 (pkg_check_modules)


cd /home/lucasw/install_base_catkin_ws/build/rviz; catkin build --get-env rviz | catkin env -si  /usr/bin/cmake /home/lucasw/base_catkin_ws/src/ros/rviz --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/lucasw/install_base_catkin_ws/devel/.private/rviz -DCMAKE_INSTALL_PREFIX=/home/lucasw/install_base_catkin_ws/install -DCMAKE_BUILD_TYPE=Release -Wno-deprecated; cd -

............................................................................................................................................................................................................................
Failed     << rviz:cmake                          [ Exited with code 1 ]                                                                                                                                                    
Failed    <<< rviz
```

This probably doesn't help
```
sudo apt install libogrenextoverlay2.2.5
```

Made this change and installed libogre 1.12 dev but not clear what the solution was, or just needed to rebuild rviz from scratch- try this fresh in a docker container or another upgrade computer
```
# find_package(OGRE QUIET COMPONENTS Overlay)
find_package(OGRE COMPONENTS Overlay)
```

anyhow now using this:

```
repositories:
  rviz:
    type: git
    url: git@github.com:lucasw/rviz.git
    version: misc_fixes
```

```
[I] [1700490835.674 ${node} ...iz/src/rviz/visualizer_app.cpp:114]: rviz version 1.14.20
[I] [1700490835.674 ${node} ...iz/src/rviz/visualizer_app.cpp:115]: compiled against Qt version 5.15.10
[I] [1700490835.674 ${node} ...iz/src/rviz/visualizer_app.cpp:116]: compiled against OGRE version 1.12.10 (Rhagorthua)
```

**Comment by lucasw** [comment]
Looks to be fully building with repos in https://github.com/lucasw/ros_from_src/commit/6b1323c17ab0a5baafa6478351c1b4517f4b6c4a (minus all the ignored ones)- but see if it builds in github action

**Comment by lucasw** [comment]
Before doing the overlay installs and just using debian packages, rospack can find std_msgs but not sensor_msgs?

-> didn't have `libsensor-msgs-dev` installed

**Comment by lucasw** [comment]
Need to update https://github.com/lucasw/image_transport_plugins enable_pub branch

`libimage-transport-dev` is causing some strange build issues on my local 23.10 system, don't install it:

```
Errors     << fuse_doc:loadenv /home/lucasw/install_base_catkin_ws/logs/fuse_doc/build.loadenv.000.log                                                                                                                          
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/catkin_tools/execution/stages.py", line 177, in function_proxy
    return function(logger, event_queue, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/catkin_tools/jobs/utils.py", line 113, in loadenv
    envs.append(get_resultspace_environment(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/catkin_tools/resultspace.py", line 130, in get_resultspace_environment
    lines = subprocess.check_output(command, cwd=os.getcwd(), env=base_env, shell=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/home/lucasw/install_base_catkin_ws/install/env.sh /bin/bash -c "env --null"' returned non-zero exit status 2.

Stage `loadenv` failed with arguments:
  job_env: {'SHELL': '/bin/bash'
```

**Comment by lucasw** [comment]
```
Errors     << lvr2:make /home/lucasw/install_base_catkin_ws/logs/lvr2/build.make.001.log                                                                                                                                        
/usr/bin/ld: CMakeFiles/lvr2_reconstruct.dir/Main.cpp.o: undefined reference to symbol 'LZ4_decompress_safe_continue'
/usr/bin/ld: /lib/x86_64-linux-gnu/liblz4.so.1: error adding symbols: DSO missing from command line
```

-> CATKIN_IGNORE for now (already put that in ignore.sh)
